[build]
builder = "NIXPACKS"
buildCommand = "composer install --no-dev --optimize-autoloader && npm install && npm run build"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT && npm run start"

releaseCommand = "php artisan migrate --seed --force"

